services:
  hono-starter-db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ${PWD}/.postgres/data:/var/lib/postgresql/data
      - ${PWD}/.postgres/db-logs:/var/log/postgresql
    networks:
      default:
    ports:
      - 5432:5432
  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meilisearch
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterkey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      default:
    volumes:
      - ${PWD}/.data.ms:/data.ms
    restart: unless-stopped
